redis:
  addr: "redis:6379"
  password: ""
  db: 0
cacheexpiration: 3600
cache:
  requireredis: false
  memorymaxsize: 10000
  memorycleaninterval: 300
port: 8043
ratelimit: 60
proxyserver: "http://127.0.0.1:8080"
proxysuffixes: []
proxyusername: ""
proxypassword: ""